# Generated by Django 5.2 on 2025-04-29 19:10

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='USER_001', max_length=255, unique=True, verbose_name='Code')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('BLOCKED', 'Bloqué'), ('SUSPENDED', 'Suspendu')], default='ACTIVE', max_length=10, verbose_name='Statut')),
                ('attempts', models.IntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('password', models.CharField(max_length=128, verbose_name='Mot de passe')),
                ('language', models.CharField(choices=[('FR', 'Français'), ('EN', 'Anglais'), ('AR', 'Arabe')], default='EN', max_length=2, verbose_name='Langue')),
                ('start_validity', models.DateTimeField(blank=True, null=True, verbose_name='Date de début de validité')),
                ('end_validity', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin de validité')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.customer', verbose_name='Client')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.profile', verbose_name='Profil')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
